Repository revanced/revanced-integrations, pull requests merged in 2022-07, with the labels that each got.

#43 fix: add missing dummy task `publish`
  build.gradle
Labels: enhancement

#50 feat: `swipe-controls`
  app/build.gradle
  app/src/main/java/app/revanced/integrations/fenster/FensterEnablement.kt
  app/src/main/java/app/revanced/integrations/fenster/WatchWhilePlayerType.kt
  app/src/main/java/app/revanced/integrations/fenster/controllers/AudioVolumeController.kt
  app/src/main/java/app/revanced/integrations/fenster/controllers/FensterController.kt
  app/src/main/java/app/revanced/integrations/fenster/controllers/FensterOverlayController.kt
  app/src/main/java/app/revanced/integrations/fenster/controllers/ScreenBrightnessController.kt
  app/src/main/java/app/revanced/integrations/fenster/util/FensterUtils.kt
  app/src/main/java/app/revanced/integrations/fenster/util/ScrollDistanceHelper.kt
  app/src/main/java/app/revanced/integrations/fenster/util/SwipeControlZoneHelper.kt
  app/src/main/java/app/revanced/integrations/patches/FensterSwipePatch.java
  app/src/main/java/app/revanced/integrations/patches/HDRMaxBrightnessPatch.java
  app/src/main/java/app/revanced/integrations/patches/VideoSwipeControlsPatch.java
  app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
  app/src/main/java/app/revanced/integrations/settingsmenu/ReVancedSettingsFragment.java
  app/src/main/java/app/revanced/integrations/videoswipecontrols/Coverage.java
  app/src/main/java/app/revanced/integrations/videoswipecontrols/Orientation.java
  app/src/main/java/app/revanced/integrations/videoswipecontrols/SwipeControlAPI.java
  app/src/main/java/app/revanced/integrations/videoswipecontrols/SwipeEventsListener.java
  app/src/main/java/app/revanced/integrations/videoswipecontrols/SwipeGestureController.java
  app/src/main/java/app/revanced/integrations/videoswipecontrols/SwipeGestureListener.java
  app/src/main/java/app/revanced/integrations/videoswipecontrols/SwipeListener.java
  app/src/main/java/app/revanced/integrations/videoswipecontrols/helpers/BrightnessHelper.java
  app/src/main/java/app/revanced/integrations/videoswipecontrols/seekbar/BrightnessSeekBar.java
  app/src/main/java/app/revanced/integrations/videoswipecontrols/seekbar/VolumeSeekBar.java
  app/src/main/res/xml/revanced_prefs.xml
  build.gradle
Labels: enhancement

#49 refactor: move settings to SettingsEnum
  app/src/main/java/app/revanced/integrations/adremover/AdRemoverAPI.java
  app/src/main/java/app/revanced/integrations/adremover/LithoAdRemoval.java
  app/src/main/java/app/revanced/integrations/patches/FensterSwipePatch.java
  app/src/main/java/app/revanced/integrations/patches/HideCreateButtonPatch.java
  app/src/main/java/app/revanced/integrations/patches/HideShortsButtonPatch.java
  app/src/main/java/app/revanced/integrations/ryd/RYDSettings.java
  app/src/main/java/app/revanced/integrations/ryd/Registration.java
  app/src/main/java/app/revanced/integrations/ryd/ReturnYouTubeDislikes.java
  app/src/main/java/app/revanced/integrations/ryd/Voting.java
  app/src/main/java/app/revanced/integrations/ryd/dialog/Dialogs.java
  app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
  app/src/main/java/app/revanced/integrations/settingsmenu/RYDSettingsFragment.java
  app/src/main/java/app/revanced/integrations/settingsmenu/ReVancedSettingsFragment.java
  app/src/main/java/app/revanced/integrations/settingsmenu/SponsorBlockSettingsFragment.java
  app/src/main/java/app/revanced/integrations/sponsorblock/PlayerController.java
  app/src/main/java/app/revanced/integrations/sponsorblock/ShieldButton.java
  app/src/main/java/app/revanced/integrations/sponsorblock/SponsorBlockSettings.java
  app/src/main/java/app/revanced/integrations/sponsorblock/SponsorBlockUtils.java
  app/src/main/java/app/revanced/integrations/sponsorblock/VotingButton.java
  app/src/main/java/app/revanced/integrations/sponsorblock/dialog/Dialogs.java
  app/src/main/java/app/revanced/integrations/sponsorblock/objects/EditTextListPreference.java
  app/src/main/java/app/revanced/integrations/sponsorblock/player/ui/NewSegmentLayout.java
  app/src/main/java/app/revanced/integrations/sponsorblock/player/ui/SBBrowserButton.java
  app/src/main/java/app/revanced/integrations/sponsorblock/player/ui/SlimButtonContainer.java
  app/src/main/java/app/revanced/integrations/sponsorblock/requests/SBRequester.java
  app/src/main/java/app/revanced/integrations/utils/LogHelper.java
  app/src/main/java/app/revanced/integrations/utils/ReVancedUtils.java
  app/src/main/java/app/revanced/integrations/videoplayer/videosettings/VideoQuality.java
  app/src/main/java/app/revanced/integrations/videoplayer/videosettings/VideoSpeed.java
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/revanced_prefs.xml
Labels: refactor

#66 fix: use Log.d for debugging
  app/src/main/java/app/revanced/integrations/adremover/LithoAdRemoval.java
  app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
  app/src/main/java/app/revanced/integrations/utils/LogHelper.java
Labels: bug

#64 feat: `swipe-controls` rewrite
  app/src/main/java/app/revanced/integrations/fenster/FensterEnablement.kt
  app/src/main/java/app/revanced/integrations/fenster/WatchWhilePlayerType.kt
  app/src/main/java/app/revanced/integrations/fenster/controllers/FensterController.kt
  app/src/main/java/app/revanced/integrations/fenster/controllers/FensterOverlayController.kt
  app/src/main/java/app/revanced/integrations/fenster/controllers/ScreenBrightnessController.kt
  app/src/main/java/app/revanced/integrations/fenster/util/SwipeControlZoneHelper.kt
  app/src/main/java/app/revanced/integrations/patches/FensterSwipePatch.java
  app/src/main/java/app/revanced/integrations/patches/PlayerTypeHookPatch.java
  app/src/main/java/app/revanced/integrations/patches/SwipeControlsPatch.java
  app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
  app/src/main/java/app/revanced/integrations/swipecontrols/SwipeControlsConfigurationProvider.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/controller/AudioVolumeController.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/controller/ScreenBrightnessController.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/controller/gesture/NoPtSSwipeGestureController.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/controller/gesture/SwipeGestureController.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/misc/Point.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/misc/Rectangle.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/misc/ScrollDistanceHelper.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/misc/SwipeControlsOverlay.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/misc/SwipeControlsUtils.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/misc/SwipeZonesHelper.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/views/SwipeControlsHostLayout.kt
  app/src/main/java/app/revanced/integrations/swipecontrols/views/SwipeControlsOverlayLayout.kt
  app/src/main/java/app/revanced/integrations/utils/Event.kt
  app/src/main/java/app/revanced/integrations/utils/PlayerType.kt
  app/src/main/java/app/revanced/integrations/utils/ReVancedUtils.java
  app/src/main/res/drawable/ic_sc_brightness_auto.xml
  app/src/main/res/drawable/ic_sc_brightness_manual.xml
  app/src/main/res/drawable/ic_sc_volume_mute.xml
  app/src/main/res/drawable/ic_sc_volume_normal.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/revanced_prefs.xml
Labels: feature-request

#81 feat: return youtube dislikes
  app/src/main/java/app/revanced/integrations/patches/ReturnYouTubeDislikesPatch.java
  app/src/main/java/app/revanced/integrations/ryd/ReturnYouTubeDislikes.java
  app/src/main/java/app/revanced/integrations/ryd/requests/RYDRequester.java
  app/src/main/java/app/revanced/integrations/sponsorblock/PlayerController.java
  app/src/main/java/app/revanced/integrations/sponsorblock/player/VideoHelpers.java
  app/src/main/java/app/revanced/integrations/sponsorblock/player/ui/AdButton.java
  app/src/main/java/app/revanced/integrations/sponsorblock/player/ui/SBBrowserButton.java
  app/src/main/java/app/revanced/integrations/sponsorblock/player/ui/SBWhitelistButton.java
  app/src/main/java/app/revanced/integrations/videoplayer/VideoInformation.java
  app/src/main/java/app/revanced/integrations/whitelist/Whitelist.java
  app/src/main/java/app/revanced/integrations/whitelist/requests/WhitelistRequester.java
Labels: feature-request

#85 feat: block `channel-guidelines`. Fixes #84
  README.md
  app/src/main/java/app/revanced/integrations/patches/GeneralBytecodeAdsPatch.java
  app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
Labels: feature-request

#95 feat: `default-video-quality` patch
  app/src/main/java/app/revanced/integrations/patches/VideoQualityPatch.java
  app/src/main/java/app/revanced/integrations/utils/ReVancedUtils.java
Labels: feature-request

#107 refactor: add missing settings to xml files and fragment
  app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
  app/src/main/java/app/revanced/integrations/settingsmenu/ReVancedSettingsFragment.java
  app/src/main/java/app/revanced/integrations/sponsorblock/SwipeHelper.java
  app/src/main/java/app/revanced/integrations/whitelist/WhitelistType.java
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/revanced_prefs.xml
Labels: change-required
